default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: postgres
  password: postgres
development:
  <<: *default
  database: employee_management_development
test:
  <<: *default
  database: employee_management_test
production:
  primary: &primary_production
    <<: *default
    database: employee_management_production
  cache:
    <<: *primary_production
    database: employee_management_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: employee_management_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: employee_management_production_cable
    migrations_paths: db/cable_migrate
